import Head from "next/head";
import { Inter } from "next/font/google";
import { Box } from "@mui/material";
import Topbar from "@/components/molecules/Topbar";
import Greeting from "@/components/atoms/Greeting";
import SearchInput from "@/components/atoms/SearchInput";
import FilterBlock from "@/components/molecules/FilterBlock";
import ProductList from "@/components/molecules/ProductList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Beer E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Topbar avatarSrc="/assets/images/avatar.jpg" />
        <Greeting name="John Doe" />
        <SearchInput />
        <FilterBlock />
        <ProductList />
      </Box>
    </>
  );
}
