import React, {PropsWithChildren} from 'react'
import { Box } from '@mui/material'
import Topbar from '@/components/molecules/Topbar'
import BottomBar from '@/components/molecules/BottomBar'
import Head from 'next/head'
import { EPageTitles } from '@/types/enums/pageTitles'

type Props = {
    children: React.ReactNode,
    hideBottomBar?: boolean,
    hideTopBar?: boolean
    title?: string
    bottomBarSlot?: React.ReactNode
}
const DefaultLayout = ({children, hideBottomBar = false, hideTopBar = false, title = EPageTitles.DEFAULT, bottomBarSlot}: Props) => {
  return (
    <>
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Box minHeight="100vh">
        {!hideTopBar && <Topbar avatarSrc="/assets/images/avatar.jpg" />}
        {children}
        {!hideBottomBar && bottomBarSlot && <BottomBar>{bottomBarSlot}</BottomBar>}
    </Box>
    </>
  )
}

export default DefaultLayout